# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Enjoy Technology
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  A set of posts to share technology finding and help to get started.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mohamedelhabib.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: elhabib_med
github_username: mohamedelhabib
linkedin_username: mohamed-el-habib-77165222

language: "en"
lang_direction: "ltr"

# PWA
color: '#fff'

# Build settings
markdown: kramdown
syntax_highlighter: coderay
highlighter: rouge

theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-toc

sass:
  style: compressed
compress_html:
  clippings: all
  comments: all
  endings: all
  profile: false
  startings: [head, body]

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

footer_content: "Copyright &copy; 2017-2019 Patrick Marsceill. Distributed by an <a href=\"https://github.com/pmarsceill/just-the-docs/tree/master/LICENSE.txt\">MIT license.</a>"
